INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE, CREATED_AT) VALUES (1, 'COMIC_BOOKS', 4, now());
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE, CREATED_AT) VALUES (2, 'BOOKS', 2, now());
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE, CREATED_AT) VALUES (3, 'MOVIES', 5, now());
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE, CREATED_AT) VALUES (4, 'MUSIC', 9, now());